inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'Gemfile'
  TargetRubyVersion: 2.3

Style/Encoding:
  Exclude:
    - 'spec/features/poll_spec.rb'

Lint/UselessAssignment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 17

Metrics/BlockLength:
  Max: 37
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Style/NestedParenthesizedCalls:
  Enabled: false

Style/PredicateName:
  NameWhitelist: has_

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Lint/UselessAccessModifier:
  Exclude:
    - 'app/models/concerns/status_machine.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/GuardClause:
  Exclude:
    - 'app/controllers/password_resets_controller.rb'
    - 'app/controllers/polls_controller.rb'

Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/controllers/polls_controller_spec.rb'
    - 'spec/controllers/users_controller_spec.rb'

Lint/AmbiguousOperator:
  Exclude:
    - 'app/models/concerns/status_machine.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'app/channels/application_cable/connection.rb'

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/password_resets_controller.rb'
